### ISSUE TITLE
how compiled with luatjit

### ISSUE THREAD

**Issue by anaquierealgo** [nycholassousa/ravendawn-client-datapack-decrypted#2]

**Comment by nycholassousa** [comment]
No need, just put the files in the same folder as the executable and delete the data.bin file.
Like this:

![image](https://github.com/nycholassousa/ravendawn-client-datapack-decrypted/assets/6095062/2b044f19-f583-4c94-b3a4-b37db1255bd9)

**Comment by nycholassousa** [comment]
If you are going to change any file, you need to force their updater not to run. To do this, leave the updater line in init.lua blank
![image](https://github.com/nycholassousa/ravendawn-client-datapack-decrypted/assets/6095062/08597c96-7e55-4fad-b087-04f7fd8937e9)

**Comment by anaquierealgo** [comment]
Thanks good Men.

**Comment by anaquierealgo** [comment]
![ravendawn_dx_zQrG9EO1Nc](https://github.com/nycholassousa/ravendawn-client-datapack-decrypted/assets/104436903/6eaa02a6-4cc0-4807-938b-8c82c5e5c2f8)

no funciona.
